export type InterfaceButtonType =
  | "undo"
  | "redo"
  | "cursor"
  | "textField"
  | "richBold"
  | "richItalic"
  | "richDirLtr"
  | "richDirRtl"
  | "richDirAuto"
  | "imgObject"
  | "newSlide"
  | "removeSlide"
  | "changeBackground"
  | "exportPdf"
  | "slideShow"
  | "hideUpperPanel";
